### ISSUE TITLE
Android Q - Can't select or take new images.

### ISSUE THREAD

**Issue by Nightfright** [esafirm/android-image-picker#238]
## Expected Behavior
Expecting it to work like pre. android q

## Actual Behavior
Can't use it at all in Android Q

## Steps to Reproduce the Problem

  1. try using it in android q
  1.
  1.

## Specifications

  - Image Picker Version: 2.1.0
  - Android OS: Android Q (10)
  - Phone: Android Studio emulator

**Comment by Nightfright** [comment]
If I change targetSdkVersion 28 it works on Android Q also.
I guess there is some new permissions in Q that later will be forced.

**Comment by ParitoshVaidya** [comment]
Does it matter if my phone has Api level 28 and my targetSdkVersion is 29?

**Comment by Nightfright** [comment]
yeah I had target api 29 and tested on android 9 then it still works.
pretty sure its this "Manage scoped external storage access" that comes with api 29 and it says it will be enforced later (now one can put target api 28 so temp. solve it)

**Comment by NM338** [comment]
can just put this in manifest. 

<application android:requestLegacyExternalStorage="true" ... >

**Comment by iverc** [comment]
Had a similar issue on Pixel 3 w/ Android 10. The picker showing gray preview instead of actual images and can't select. Fixed it by adding `<application android:requestLegacyExternalStorage="true"` in `AndroidManifest`. @NM338 Thanks!

**Comment by esafirm** [comment]
Hey guys this issue should be fixed in 2.3.0. Thanks!

**Comment by Helgard-Bitcube** [comment]
Still getting the same issue on 2.3.2, when I take a photo it works fine but when I select a gallery image it throws a EACCES (Permission denied) exception. Was able to fix it for now by adding `<application android:requestLegacyExternalStorage="true" ... >` to the manifest as suggested but this won't work from API level 30. See https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage

**Comment by Jatindersyall12** [comment]
This issue is not resolved for android 11 please help
