### ISSUE TITLE
Android 10: Image Picker showing Gray images in the image picking activity and when a image is selected app crashes.

### ISSUE THREAD

**Issue by onirban27** [esafirm/android-image-picker#253]
## Expected Behavior
Show images in the image picker

## Actual Behavior
shows gray thumbnails in the image picker activity

## Steps to Reproduce the Problem

  1. Android 10 device
  2. Open image picker
  3. Select a image

## Specifications

  - Image Picker Version: 2.2.0
  - Android OS: 10
  - Phone: One Plus 7 Pro

**Comment by onirban27** [comment]
i was able to fix this problem by adding this in my manifest. but i guess this is temporary solution.
`<manifest ... >
    
    <application android:requestLegacyExternalStorage="true" ... >
     ...
    </application>
</manifest>`

**Comment by StephanWalters** [comment]
OMG Thank you!

> i was able to fix this problem by adding this in my manifest. but i guess this is temporary solution.
> `<manifest ... > <!-- This attribute is "false" by default on apps targeting Android Q. --> <application android:requestLegacyExternalStorage="true" ... > ... </application> </manifest>`

**Comment by simon-the-canadian** [comment]
`android:requestLegacyExternalStorage="true"` won't be allowed when targeting Android 11. Would be nice to have an update that handles images on Android 10 and up sooner than later. 

https://developer.android.com/preview/privacy/storage

**Comment by jarrodparkes** [comment]
just recently ran into this bug. using the workaround for now, but +1 for an update that handles newer versions of Android

**Comment by NinhvanLuyen** [comment]
Thanks, @onirban27, But I think we need clarity reason from google. Because recently I updated the app to play store, My user have been announcement this is bug for me.

**Comment by esafirm** [comment]
Hey guys, this should be fixed on version 2.3.0
Stay safe!

**Comment by SanthoshPnGowda** [comment]
Its not fixed,its throw an exception  file not found(EACCESS DENIED),because scoped storage is not working,if i enable legacy storage true in manifest.its working fine
