### ISSUE TITLE
Image is not showing after selection

### ISSUE THREAD

**Issue by onirban27** [esafirm/android-image-picker#254]
## Expected Behavior
After selecting the image it will show in the image view.
## Actual Behavior
shows nothing. throwing error.

## Steps to Reproduce the Problem

  1. use legecyExternalStorage = true in manifest
  2. select a image file
  3. shows empty file

## Specifications

  - Image Picker Version: 2.2.0
  - Android OS: 10
  - Phone: One Plus 7 Pro

## Error Log
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid byte order: ffff8950
        at android.media.ExifInterface.readByteOrder(ExifInterface.java:3121)
        at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2437)
        at android.media.ExifInterface.getMimeType(ExifInterface.java:2315)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1753)
        at android.media.ExifInterface.<init>(ExifInterface.java:1447)
        at com.bumptech.glide.load.resource.bitmap.p.a(:40)
        at com.bumptech.glide.load.b.a(:92)
        at com.bumptech.glide.load.resource.bitmap.m.a(:269)
        at com.bumptech.glide.load.resource.bitmap.m.a(:224)
        at com.bumptech.glide.load.resource.bitmap.m.a(:173)
        at com.bumptech.glide.load.resource.bitmap.g.a(:31)
        at com.bumptech.glide.load.resource.bitmap.g.a(:14)
        at com.bumptech.glide.load.engine.g.a(:92)
        at com.bumptech.glide.load.engine.g.a(:70)
        at com.bumptech.glide.load.engine.g.a(:59)
        at com.bumptech.glide.load.engine.q.a(:76)
        at com.bumptech.glide.load.engine.q.a(:57)
        at com.bumptech.glide.load.engine.DecodeJob.a(:524)
        at com.bumptech.glide.load.engine.DecodeJob.a(:488)
        at com.bumptech.glide.load.engine.DecodeJob.a(:474)
        at com.bumptech.glide.load.engine.DecodeJob.e(:426)
        at com.bumptech.glide.load.engine.DecodeJob.a(:390)
        at com.bumptech.glide.load.engine.t.a(:123)
        at com.bumptech.glide.load.k.d$a.a(:70)
        at com.bumptech.glide.load.engine.t.a(:102)
        at com.bumptech.glide.load.engine.DecodeJob.k(:310)
        at com.bumptech.glide.load.engine.DecodeJob.l(:276)
        at com.bumptech.glide.load.engine.DecodeJob.run(:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.y.a$a$a.run(:431)
I/chatty: uid=10294(com.gogaffl.gaffl) glide-disk-cach identical 3 lines
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid byte order: ffff8950
        at android.media.ExifInterface.readByteOrder(ExifInterface.java:3121)
        at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2437)
        at android.media.ExifInterface.getMimeType(ExifInterface.java:2315)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1753)
        at android.media.ExifInterface.<init>(ExifInterface.java:1447)
        at com.bumptech.glide.load.resource.bitmap.p.a(:40)
        at com.bumptech.glide.load.b.a(:92)
        at com.bumptech.glide.load.resource.bitmap.m.a(:269)
        at com.bumptech.glide.load.resource.bitmap.m.a(:224)
        at com.bumptech.glide.load.resource.bitmap.m.a(:173)
        at com.bumptech.glide.load.resource.bitmap.g.a(:31)
        at com.bumptech.glide.load.resource.bitmap.g.a(:14)
        at com.bumptech.glide.load.engine.g.a(:92)
        at com.bumptech.glide.load.engine.g.a(:70)
        at com.bumptech.glide.load.engine.g.a(:59)
        at com.bumptech.glide.load.engine.q.a(:76)
        at com.bumptech.glide.load.engine.q.a(:57)
        at com.bumptech.glide.load.engine.DecodeJob.a(:524)
        at com.bumptech.glide.load.engine.DecodeJob.a(:488)
        at com.bumptech.glide.load.engine.DecodeJob.a(:474)
        at com.bumptech.glide.load.engine.DecodeJob.e(:426)
        at com.bumptech.glide.load.engine.DecodeJob.a(:390)
        at com.bumptech.glide.load.engine.t.a(:123)
        at com.bumptech.glide.load.k.d$a.a(:70)
        at com.bumptech.glide.load.engine.t.a(:102)
        at com.bumptech.glide.load.engine.DecodeJob.k(:310)
        at com.bumptech.glide.load.engine.DecodeJob.l(:276)
        at com.bumptech.glide.load.engine.DecodeJob.run(:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.y.a$a$a.run(:431)

**Comment by onirban27** [comment]
This is a Glide issue for android 10 and fixed in Glide 4.10.0. kindly update the glide library for this image picker to 4.10.0.

**Comment by GauravRana** [comment]
Use Glide to set bitmap as image::
 Glide.with(this)
                    .asBitmap()
                    .load(bitmap)
                    .apply(RequestOptions)
                    .into(imageView)

**Comment by esafirm** [comment]
@onirban27 we have Glide 4.11.0 in 2.3.0
Can you confirm do the issue still remain?

**Comment by IbrahimSayed94** [comment]
add android:requestLegacyExternalStorage="true"  to application tag on manifest

**Comment by esafirm** [comment]
This should not exist in 2.4.5 or 3.x
