### ISSUE TITLE
The image file could not be opened in targetsdkversion 29

### ISSUE THREAD

**Issue by codehack26** [esafirm/android-image-picker#258]
## Expected Behavior
Set / change profile picture

## Actual Behavior
ERROR:The image file could not be opened

## Specifications

  - Image Picker Version: 2.1.10
  - Android OS:10
  - Phone: Nokia 8.1

**Code :**

```
openGallery():Promise<string>{
    return new Promise((resolve,reject)=>{
      this.checkPermission().then(granted=>{
        if (granted) {

          let options = {
            quality:80,
            maximumImagesCount:1
          };

          this.picker.getPictures(options).then(uri=>{
            console.log("URI of picked image "+uri);
            this.cropImage(uri.toString()).then(croppedImage=>{
              resolve(croppedImage);
            }).catch(err=>{
              reject("error in cropIMage "+JSON.stringify(err));
              console.log("error in getPrictures_crop "+JSON.stringify(err))
            })
          }).catch(err=>{
             reject("error in getPictures "+JSON.stringify(err));
             console.log("getPictures "+err);
          })
        }
      })
    })
  }

```

**Comment by hirenpatel868** [comment]
android:requestLegacyExternalStorage="true" add this to your manifest file

**Comment by phucnguyensna** [comment]
Many thanks @hirenpatel868 . It works perfect.

**Comment by djdance** [comment]
great, I've faced with it too. Thanks. I think, author must add this to the main page

**Comment by mortezaRahimi** [comment]
android:requestLegacyExternalStorage="true" is temporary and it is not work while your app published in Google Play.

Right now i have this issue in my app.

**Comment by sameerjj** [comment]
> android:requestLegacyExternalStorage="true" is temporary and it is not work while your app published in Google Play.
> 
> Right now i have this issue in my app.

Simply not true. Published and having no issues. Also google documentation states nothing about such things. Please be careful with spreading fake info. However targeting API level 30, this fix will not work. works for 29 only.

**Comment by esafirm** [comment]
Hey guys this issue should be fixed in 2.3.0
Thanks!

**Comment by SanthoshPnGowda** [comment]
Not resolved,still getting an error
Caused by: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/IMG_20200604_112539.jpg: open failed: EACCES (Permission denied) android 10

**Comment by codehack26** [comment]
> android:requestLegacyExternalStorage="true" add this to your manifest file

error: No resource identifier found for attribute 'requestLegacyExternalStorage' in package 'android'

This is what I am getting when I add android:requestLegacyExternalStorage="true" in manifest file

Unable to build APK
![Image picker](https://user-images.githubusercontent.com/59353691/85679985-86978900-b6e7-11ea-8220-aa761684dbf1.png)

**Comment by sameerjj** [comment]
> > android:requestLegacyExternalStorage="true" add this to your manifest file
> 
> error: No resource identifier found for attribute 'requestLegacyExternalStorage' in package 'android'
> 
> This is what I am getting when I add android:requestLegacyExternalStorage="true" in manifest file
> 
> Unable to build APK
> ![Image picker](https://user-images.githubusercontent.com/59353691/85679985-86978900-b6e7-11ea-8220-aa761684dbf1.png)

are u using `targetSdkVersion 29` `compileSDKVersion 29`

**Comment by codehack26** [comment]
> > > android:requestLegacyExternalStorage="true" add this to your manifest file
> > 
> > 
> > error: No resource identifier found for attribute 'requestLegacyExternalStorage' in package 'android'
> > This is what I am getting when I add android:requestLegacyExternalStorage="true" in manifest file
> > Unable to build APK
> > ![Image picker](https://user-images.githubusercontent.com/59353691/85679985-86978900-b6e7-11ea-8220-aa761684dbf1.png)
> 
> are u using `targetSdkVersion 29` `compileSDKVersion 29`

Yes I am using targetSdkVersion 29

**Comment by sameerjj** [comment]
```
 <application
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true">

```

**Comment by codehack26** [comment]
> ```
>  <application
>         android:label="@string/app_name"
>         android:requestLegacyExternalStorage="true">
> ```

Yes, @sameerjj I tried the same but still, I am getting the same error.
