### ISSUE TITLE
Pictures taken with camera dissapears in api29 (multimode not working with camera)

### ISSUE THREAD

**Issue by Nightfright** [esafirm/android-image-picker#280]
## Expected Behavior
When taking a photo with the camera I expect to be able to select it (multi mode)

## Actual Behavior
After taking a picure i get returned to the image selection part and the new image is not to be found (its not found in gallery either).

## Steps to Reproduce the Problem

.showCamera(true)
                    .folderMode(true)
                    .imageDirectory("mydirectory")

if I add .returnMode(ReturnMode.CAMERA_ONLY) then i get the image and can use it, but its not in gallery and this is a workaround since it won't work when you want multiselect

I think it's because on older api it is saved in 
/storage/emulated/0/Pictures/myfolder/IMG_20200630_114736_962.jpg

and with new api (tested with and without requestlegacystorage)
/storage/emulated/0/Android/data/se.mypackagename.xxxx.debug/files/Pictures/myfolder/IMG_20200630_140814_772.jpg

I suspect there is a missing call to index the file or something?

## Specifications

  - Image Picker Version: 2.3.1
  - Android OS: api29 (Android 10)
  - Phone: Samsung Galaxy z-flip

**Comment by Nightfright** [comment]
Another workaround is if you have WRITE_EXTERNAL_STORAGE permission
is to
File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES + "/myfolder/");
            path.mkdirs();
            ImagePicker.create(JournalReportFragment.this)
                    .showCamera(true)
                    .folderMode(true)
                    .imageFullDirectory(path.getAbsolutePath())

This will revert to old working (for now) way

**Comment by vajiralasantha** [comment]
> Another workaround is if you have WRITE_EXTERNAL_STORAGE permission
> is to
> File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES + "/myfolder/");
> path.mkdirs();
> ImagePicker.create(this)
> .showCamera(true)
> .folderMode(true)
> .imageFullDirectory(path.getAbsolutePath())
> 
> This will revert to old working (for now) way

Fixed my issue. Any word on an official fix?

**Comment by rahul4452** [comment]
> Another workaround is if you have WRITE_EXTERNAL_STORAGE permission
> is to
> File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES + "/myfolder/");
> path.mkdirs();
> ImagePicker.create(this)
> .showCamera(true)
> .folderMode(true)
> .imageFullDirectory(path.getAbsolutePath())
> 
> This will revert to old working (for now) way

Thanks for this workaround.

**Comment by hoajb** [comment]
> Another workaround is if you have WRITE_EXTERNAL_STORAGE permission
> is to
> File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES + "/myfolder/");
> path.mkdirs();
> ImagePicker.create(this)
> .showCamera(true)
> .folderMode(true)
> .imageFullDirectory(path.getAbsolutePath())
> 
> This will revert to old working (for now) way

Thanks. It worked for me.

Image Picker Version: 2.3.2
Android OS: api29 (Android 10)
Phone: Samsung Galaxy A11

**Comment by hjchin** [comment]
it does not work for me. 

Based on the log, 
File /storage/emulated/0/Android/data/xxx/files/Pictures/myfolder/IMG_20200925_163431_588.jpg was scanned successfully: null

the URI after scanning is null. 

it works in API 27.

**Comment by hjchin** [comment]
I have the code for Android Q, after watching and reading the docs, finally. I will raise a PR soon.

**Comment by esafirm** [comment]
Should be fixed by now

**Comment by dfabreguette-ap** [comment]
master branch does not fix the problem for use with Android Q devices (Huawei P30 pro for example).
Any chances the next realease will be ready soon ?
