### ISSUE TITLE
Cannot display media file right under root directory in Folder mode

### ISSUE THREAD

**Issue by wiwuwa** [esafirm/android-image-picker#333]
## Expected Behavior
Display media file right under /storage/emulated/0/

## Actual Behavior
Cannot display media file right under /storage/emulated/0/
Only Huawei phone can display it, others cannot.
## Steps to Reproduce the Problem

  1. Move a media file (e.g. .jpg) right under /storage/emulated/0/
  2. Use Image Picker with folder mode
  3. File did not display in folder mode in Image Picker Version 2.4.2
  4. App Crash in Image Picker Version 2.4.0

## Specifications

  - Image Picker Version: 2.4.2
  - Android OS: 9, 10
  - Phone: Samsung, LG

**Comment by esafirm** [comment]
Fixed on 2.4.3

**Comment by rahul4452** [comment]
@esafirm Still facing the same issue in 2.4.3 

java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:77)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:163)
        at com.esafirm.imagepicker.helper.ImagePickerUtils.getVideoDurationLabel(ImagePickerUtils.java:114)
        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.kt:67)
        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.kt:23)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:22092)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:22092)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22092)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:22092)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22092)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22092)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22092)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22092)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:810)
        at android.view.View.layout(View.java:22092)
        at android.view.ViewGroup.layout(ViewGroup.java:6325)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3191)
